apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ln-terminal.fullname" . }}-conf
  labels:
    {{- include "ln-terminal.labels" . | nindent 4 }}
data:
  lit.conf: |-
  {{- range .Values.configuration }}
    {{ . }}
  {{- end }}
    remote.lnd.rpcserver={{ .Values.lnd.host }}:{{ .Values.lnd.port }}
