apiVersion: v1
kind: Service
metadata:
  name: {{ include "ln-terminal.fullname" . }}
  labels:
    {{- include "ln-terminal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "ln-terminal.selectorLabels" . | nindent 4 }}
